theme: minima
title: marecki.net - blog
author: PawlakMarek
email: marek@marecki.net
description: > # this means to ignore newlines until "baseurl:"
  My private blog about IT, comic books, cuisine and everything I'd find interesting.

# social links
github_username:  PawlakMarek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
